feature/155_ci_build_3_9
ualibraries/LD_Cool_P pull request #158
Opened 2021-02-02 17:12 UTC by damian-romero

See #155

2021-02-02 17:53 UTC, astrochun requested changes
Changes look good. Just a few suggestions to README.md.  Includes update to `pandas` version.

Still need to update `numpy` version

2021-02-02 17:53 UTC, astrochun commented on README.md
> +1. Python >= v3.7.9
```suggestion
1. Python (>=v3.7.9)
```

2021-02-02 17:53 UTC, astrochun commented on README.md
>  3. [`pandas`](https://pandas.pydata.org/) ([1.0.2](https://pandas.pydata.org/pandas-docs/version/1.0.2/))
```suggestion
3. [`pandas`](https://pandas.pydata.org/) ([1.2.1](https://pandas.pydata.org/pandas-docs/version/1.2.1/))
```

2021-02-02 17:53 UTC, astrochun commented on README.md
> +First, install a working version of Python >= v3.7.9.  We recommend using the
```suggestion
First, install a working version of Python (>=3.7.9).  We recommend using the
```

2021-02-03 22:03 UTC, damian-romero commented on README.md
> +5. [`numpy`](https://numpy.org/) ([1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html)).17.4))
Fix typo
```suggestion
5. [`numpy`](https://numpy.org/) ([1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html))
```

2021-02-05 18:43 UTC, astrochun approved these changes
Changes look good.

2021-02-05 18:50 UTC, merged